angular.module('restaurantApp',[])
.controller('MenuController', function()
{
    var dishes = 
    [
        {name:'Ēdiens#1', image:'images/food1.jpg', category:'specials', price:'4.00', description:'Šis ēdiens jums noteikti jānogaršo. Maecenas vel interdum massa. Nam nec justo a dui tempus aliquam. Suspendisse sollicitudin lacus non ligula vehicula tincidunt. Maecenas venenatis eros ac malesuada placerat. Fusce in aliquet purus, in iaculis sapien. Vivamus nec sem nibh. Nunc aliquet nisl nec nunc egestas, eu ornare risus accumsan. Suspendisse ligula mi, consectetur nec lacus eget, sollicitudin laoreet nulla. In hac habitasse platea dictumst. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dictum tincidunt mauris quis tincidunt. Maecenas laoreet massa erat, non volutpat elit faucibus ultrices. Integer dapibus ac nibh at aliquet. Suspendisse sed turpis ac magna rutrum aliquam.'},
        {name:'Ēdiens#2', image:'images/food2.jpg', category:'specials', price:'6.00', description:'Šis ēdiens jums noteikti jānogaršo. Maecenas vel interdum massa. Nam nec justo a dui tempus aliquam. Suspendisse sollicitudin lacus non ligula vehicula tincidunt. Maecenas venenatis eros ac malesuada placerat. Fusce in aliquet purus, in iaculis sapien. Vivamus nec sem nibh. Nunc aliquet nisl nec nunc egestas, eu ornare risus accumsan. Suspendisse ligula mi, consectetur nec lacus eget, sollicitudin laoreet nulla. In hac habitasse platea dictumst. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dictum tincidunt mauris quis tincidunt. Maecenas laoreet massa erat, non volutpat elit faucibus ultrices. Integer dapibus ac nibh at aliquet. Suspendisse sed turpis ac magna rutrum aliquam.'},
        {name:'Ēdiens#3', image:'images/food3.jpg', category:'vegetarian', price:'5.00', description:'Šis ēdiens jums noteikti jānogaršo. Maecenas vel interdum massa. Nam nec justo a dui tempus aliquam. Suspendisse sollicitudin lacus non ligula vehicula tincidunt. Maecenas venenatis eros ac malesuada placerat. Fusce in aliquet purus, in iaculis sapien. Vivamus nec sem nibh. Nunc aliquet nisl nec nunc egestas, eu ornare risus accumsan. Suspendisse ligula mi, consectetur nec lacus eget, sollicitudin laoreet nulla. In hac habitasse platea dictumst. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dictum tincidunt mauris quis tincidunt. Maecenas laoreet massa erat, non volutpat elit faucibus ultrices. Integer dapibus ac nibh at aliquet. Suspendisse sed turpis ac magna rutrum aliquam.'},
        {name:'Ēdiens#4', image:'images/food4.jpg', category:'vegetarian', price:'6.99', description:'Šis ēdiens jums noteikti jānogaršo. Maecenas vel interdum massa. Nam nec justo a dui tempus aliquam. Suspendisse sollicitudin lacus non ligula vehicula tincidunt. Maecenas venenatis eros ac malesuada placerat. Fusce in aliquet purus, in iaculis sapien. Vivamus nec sem nibh. Nunc aliquet nisl nec nunc egestas, eu ornare risus accumsan. Suspendisse ligula mi, consectetur nec lacus eget, sollicitudin laoreet nulla. In hac habitasse platea dictumst. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dictum tincidunt mauris quis tincidunt. Maecenas laoreet massa erat, non volutpat elit faucibus ultrices. Integer dapibus ac nibh at aliquet. Suspendisse sed turpis ac magna rutrum aliquam.'},
        {name:'Ēdiens#5', image:'images/food5.jpg', category:'vegan', price:'5.00', description:'Šis ēdiens jums noteikti jānogaršo. Maecenas vel interdum massa. Nam nec justo a dui tempus aliquam. Suspendisse sollicitudin lacus non ligula vehicula tincidunt. Maecenas venenatis eros ac malesuada placerat. Fusce in aliquet purus, in iaculis sapien. Vivamus nec sem nibh. Nunc aliquet nisl nec nunc egestas, eu ornare risus accumsan. Suspendisse ligula mi, consectetur nec lacus eget, sollicitudin laoreet nulla. In hac habitasse platea dictumst. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dictum tincidunt mauris quis tincidunt. Maecenas laoreet massa erat, non volutpat elit faucibus ultrices. Integer dapibus ac nibh at aliquet. Suspendisse sed turpis ac magna rutrum aliquam.'},

    ];
    this.dishes = dishes;

})